### ISSUE TITLE
Runtime error when viewing T-Shirt product

### ISSUE THREAD

**Issue by bacteriaman** [mglaman/commerce_demo#12]
After enabling commerce_demo with a fresh install of Drupal 8.2.3 and current version of Commerce 8.x-2.x-dev the following error occurs when attempting to view a newly created T-Shirt product: "The website encountered an unexpected error. Please try again later." The error log shows a long error message (too long to paste here), but the message begins with "Error: Call to a member function getPurchasableEntityTypeId() on null in Drupal\commerce_order\Entity\OrderItem::bundleFieldDefinitions()"

As per mglaman in #drupal-commerce, the Order Item Type must be set to "Default" on the T-Shirt Product Variation type edit page (admin/commerce/config/product-variation-types/t_shirt/edit).

**Comment by mglaman** [comment]
This was fixed
