### ISSUE TITLE
Couldn't install the module. Shipments field exists

### ISSUE THREAD

**Issue by ygerasimov** [mglaman/commerce_demo#22]
When I tried to install the module I had an error thrown: field "shipments" exists. After removing config files field.field.commerce_order.default.shipments.yml and field.storage.commerce_order.shipments.yml module was installed successfully

**Comment by mglaman** [comment]
Hm. @ygerasimov did your site already have commerce_shipping enabled?

**Comment by mglaman** [comment]
@ygerasimov Yep, saw that. It's fixed now on travis. Thanks for reporting!
