### ISSUE TITLE
How to export products?

### ISSUE THREAD

**Issue by edwardaa** [mglaman/commerce_demo#24]
There are **demo_tbooks.csv** and **demo_t_shirts.csv** files, are these files exported by any module, or created manually?

I created a module and want it to ship with some default products with images.

Thanks for your cool demo, it helps a lot.

**Comment by tormi** [comment]
You can use [csv_serialization](https://www.drupal.org/project/csv_serialization) module for csv export, there is a step-by-step tutorial "How to create a CSV view" available.

**Comment by edwardaa** [comment]
Thanks for your quick reply, I'll try it

**Comment by mglaman** [comment]
Thanks @tormi. I had made these manually.
