### ISSUE TITLE
Description column from CSV not imported

### ISSUE THREAD

**Issue by jpdaut** [mglaman/commerce_demo#6]
Data from Description column is not imported by migrate.  Was it meant for the Body field of Product?  It's not happening..

**Comment by jpdaut** [comment]
This works great now in the latest code.

Just a note that since Body is at product type level, Description column does not need to repeat it for every variation row on a product. Minor point.

**Comment by mglaman** [comment]
@jpdaut this is true. But this is how a lot of ERP's may output the CSV.

This sample is pretty much to help people see how to convert the duplicated content.
