### ISSUE TITLE
composer.json requires

### ISSUE THREAD

**Issue by jpdaut** [mglaman/commerce_demo#7]
I believe the composer.json requires should be 

```
  "require": {
      "drupal/commerce": "8.x-2.x-dev",
      "drupal/commerce_migrate": "8.x-2.x-dev",
      "drupal/migrate_plus": "8.x-2.x-dev",
      "drupal/migrate_source_csv": "8.x-2.x-dev",
      "drupal/migrate_tools": "8.x-2.x-dev"
  }
```

**Comment by mglaman** [comment]
Ah because that's the branch alias. Actually, the `2.x-dev` is how the dev release is labeled in Drupal's packagist endpoint.

**Comment by mglaman** [comment]
We're using drupal's package endpoint

**Comment by jpdaut** [comment]
I'd forgotten to reply but yes, I completely agree  Thanks.
