### ISSUE TITLE
OrderTypeResolverInterface not implemented

### ISSUE THREAD

**Issue by jpdaut** [mglaman/commerce_demo#9]
Hi
I'm getting this error installing the latest code : 

Symfony\Component\DependencyInjection\Exception\LogicException: Service 'commerce_demo.product_type_order_type_resolver' for consumer 'commerce_order.chain_order_type_resolver' does not implement Drupal\commerce_order\Resolver\OrderTypeResolverInterface. in Drupal\Core\DependencyInjection\Compiler\TaggedHandlersPass->process() (line 125 of /home/ssd8oos/cdemo/web/core/lib/Drupal/Core/DependencyInjection/Compiler/TaggedHandlersPass.php).

**Comment by mglaman** [comment]
Yes, I'm an idiot and commited the file structure wrong :) Working on fix

**Comment by mglaman** [comment]
Pushed

**Comment by jpdaut** [comment]
Yes it works now. Thanks!
